orbitdeterminator/main.py
orbitdeterminator/util/read_data.py

Added commandline arguments functionality. (fixes #100)
Simplified utils.read_data.load_data function.

Commandline arguments

---

README.md

Tweaks to the readme

---

orbitdeterminator/kep_determination/gibbs_method.py
orbitdeterminator/kep_determination/graphics.py

Implemented using class in python2. Working on the update for compatibility.

Implementation of Gibb's Method

---

orbitdeterminator/kep_determination/lamberts_kalman.py
orbitdeterminator/main.py
orbitdeterminator/util/state_kep.py

Fixes #99.
Sets multi_rev to 0 in lamberts_kalman.py. This makes the output array have the required shape.
Limits the cosines in state_kep.py to be between -1 and 1. Sometimes, due to floating point errors, it can go out of limit.
Adds a new command line option to choose between metres and kilometres.

Fixes issue 99

---

orbitdeterminator/kep_determination/ellipse_fit.py

Implemented residuals in ellipse fit and fixed some minor issues.

Implemented residuals in ellipse fit.

---

orbitdeterminator/tests/test_ellipse_fit.py

Added tests for 3 satellites:
* NOAA-1
* GPS-23
* Cryosat-2

Added tests for ellipse fit

---

orbitdeterminator/database/init_database.py
orbitdeterminator/database/scraper.py
orbitdeterminator/kep_determination/gibbs_method.py
orbitdeterminator/kep_determination/graphics.py

The database is on MySQL. Use your username and password in the appropriate field to access your database.

Database Scraper

---

README.md

Updated installation guide for installation in Windows/macOS based system as the previous guide didn't take into account that 'pykep' has issues on macOS and Windows. It'll help users with Issue #149

Updated Installation Guide

---

orbitdeterminator/kep_determination/interpolation.py
orbitdeterminator/main.py
requirements.txt

The user can now select which filters and methods he wants to use for orbit determination, the Gibbs method has not been implemented right now as it has some errors.
Working of main.py right now is such that First user will get a prompt asking which filters he wants to use (filters are applied in order i.e if he selects Savintzky Golay Filter then selects Triple Moving Average then first Golay filter will be applied then Triple moving average filter). After that, a user will have to choose Methods for orbit determination (if nothing selected, spline interpolation will be used by default).
As of now, we are not plotting orbit for all the methods, the orbit will be plotted for only the first method which user selects, it can be changed in future as per the guidelines from maintainers. …

Added user option to select Filters and Methods to use for orbit determination

---

orbitdeterminator/kep_determination/custom_prop.py
orbitdeterminator/kep_determination/gauss_method.py
requirements.txt

Add a script that allows the user to propagate keplerian elements generated by gauss method. Propagation module consists of environments for various natural and artificial perturbation accelerations. User can select ephemeris for sun orbiting bodies both while applying gauss method and while propagating. Add option to select SGP4/SDP models for the propagation of earth orbiting satellites. User can change the values of various natural constants or use the default ones. Add option to use NASA NEO Webservice for (comets and asteroids) NEOs orbital data and add method for their propagation. Prints initial orbital elements and final (position, velocity) vectors and final orbital elements. 
Add support for all angle subformats in IOD format used by satobs.
Files changed: created …

Custom propagation module in various customizable perturbation environments, support for angle sub-formats(IOD)

---

.gitignore
requirements.txt

Reverts aerospaceresearch/orbitdeterminator#163
@aakash525 Please make necessary changes according to CONTRIBUTING.md

Revert "update requirements.txt and to sync my fork"

---

orbitdeterminator/kep_determination/gauss_method.py
orbitdeterminator/kep_determination/least_squares.py

Files changed: least_squares.py, gauss_method.py
Purpose: Add option to use weighted least squares method, add option to take into account light propagation time.

Add weights to least squares subroutines and an option to take into account light propagation time

---

orbitdeterminator/kep_determination/custom_prop.py

Files changed: custom_prop.py
Aim: Adding 3-d plots

Add 3-d plot for satellite location

---

orbitdeterminator/util/conversion_module.py

Files changed: Created conversion_module.py
Purpose: Adding functions to do various conversions that are useful in orbit determination.

Add conversion module, acquires various conversion functions useful in orbit determination

---

orbitdeterminator/propagation/sgp4.py

Resolved Math Domain Error issue #183

Minor Bug Fix

---

setup.py

Resolved minor dependency issue due to missing '**inquirer**' package in setup.py #181

Minor dependency fix

---

orbitdeterminator/kep_determination/gauss_method.py
orbitdeterminator/kep_determination/least_squares.py

adds more IOD formats, but not all.
Formats 1,2,3&7 are included now. for 4,5&6 we need to add El/AZ to RA/DEC conversion.
and also some formating cleansing

Positional obs report formats

---

orbitdeterminator/main.py
orbitdeterminator/propagation/sgp4.py

fixeds the correct linkage to the imported lib. sorry, just forgot it when renaming the file.

fixed lib names

---

orbitdeterminator/main.py

fixed another gibbs_method link

fixed another gibbs_method link

---

.travis.yml
orbitdeterminator/animate_orbit.py
requirements.txt
setup.py

adds requirements install
adds python 3.8, because travis did not build in 3.5 anymore.
adds pygmo to the requirements.txt

adds requirements install and adds python 3.8

---

orbitdeterminator/kep_determination/gauss_method.py
orbitdeterminator/kep_determination/sat_tracking_observatories.txt
requirements.txt

Remove pyephem dependency

---

orbitdeterminator/kep_determination/gauss_method.py
orbitdeterminator/kep_determination/orbital_elements.py
orbitdeterminator/main.py

Preliminary orbit determination
